Feature branch
Mutai-Gilbert/Responsive-Personal-Porfolio pull request #2
Opened 2022-09-24 21:11 UTC by Mutai-Gilbert

This is the continuation of the portfolio-mobile projects using html and css

2022-09-24 22:03 UTC, Tadesse-Alemayehu requested changes
Hi @Mutai-Gilbert 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-done-ashley-garcia](https://user-images.githubusercontent.com/69077061/192120180-ef1f08de-478b-49a5-900e-c84803803aeb.gif)


## Highlights
- Linter is set up correctly for this repository. ✔
- The README file is descriptive. ✔
- Use the correct GitHub flow. ✔
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +  </section>
- Good job on the cards. Also, Make sure to incorporate the following 
- [ ] All the cards should be inside a `wok/container/projects` section. 
- [ ] The main container of the `projects/cards` should have a `display: grid`
- [ ] add the margins (top, bottom, left, right) and font, colors (background and font) defined in the design to the  `wok/container/projects` section you are going to create to wrap your projects.

### [Figma Design](figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

![figma](https://user-images.githubusercontent.com/69077061/192120005-f44f7243-51b2-450f-be1c-4c3fd5b1d033.PNG)

### Your Design

![your](https://user-images.githubusercontent.com/69077061/192120008-e813e2dd-d7da-4e62-b8ee-3180e607c0d6.PNG)

2022-09-24 22:03 UTC, TadesseDev commented on styles.css
> +}
- [ ] Make sure the content of the project is aligned with the `flexbox`. The `display: grid` should be set for the container of the projects.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +      </h4>
- [ ] Kindly, remember to use the `p ` tag for paragraphs, as it will play a great role when it comes to semantics.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +    </div>
- [ ] Kindly, remember to use the `a` or `button` tag for buttons, as it will play a great role when it comes to semantics.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +      <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
- [ ] Kindly, remember to use the `p ` tag for paragraphs, as it will play a great role when it comes to semantics.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +    </div>
- [ ] Kindly, remember to use the `a` or `button` tag for buttons, as it will play a great role when it comes to semantics.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +      <h5>Languages</h5>
- [ ] Kindly, remember to use the `a` or `button` tag for buttons, as it will play a great role when it comes to semantics.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +    </div>
- [ ] Good job so far. Also, it would be great to use `li` for the `framework` and `skill` as the project requirement.

2022-09-24 22:03 UTC, TadesseDev commented on index.html
> +</main>
- [ ] Kindly, make sure the container of the about me section is a `section` tag. This will add semantic meaning to your portfolio.
- [ ] Also, the display should be set to `flexbox` as part of the project requirement.
- [ ] Remember, The section should use the margins (top, bottom, left, right) defined in the design. 
- [ ] Remember, The section should the font and colors (background and font) defined for the template.

### [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
![figma](https://user-images.githubusercontent.com/69077061/192119952-6fa57b2a-e57f-47ac-b81e-e9b21f99774b.PNG)

### Your design 
![your](https://user-images.githubusercontent.com/69077061/192119957-b9eb492e-5e9e-409d-b61f-078980fd9788.PNG)

2022-09-24 23:40 UTC, Alfredbis29 requested changes
Hi @Mutai-Gilbert ,
 
 # Status: Changes Required 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

![a little more](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif) 

 ## Good Highlights
 * Linter checks are passing
* Adherence to GitHub flow
* Description for pull request has been added
 
 ## Required Changes 
 * Kindly ensure that you follow the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) to complete the sections (including styling) required for the current milestone. The to sections expected are the toolbar (or header) and the headline section (right after the header). You seem to have added sections that are meant to be in a future milestone.

 
 * _Check the comments under the review for more comments._
 
 Cheers and Happy coding!clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 23:40 UTC, Alfredbis29 commented on styles.css
> +  background-color: #e5e5e5;
- [ ]  Good job so far but you still need some improvement for your project to look awesome , As we are imitate Figama Design and if we compare your design to the figma one are not matching , your design should look the same as the figma design given for this template 😉 
Your Design 👇 
![man1](https://user-images.githubusercontent.com/88894525/192122051-79702802-c1b0-4522-b0ec-ad83a72096eb.png)

Figma Design 👇 

![figmaman](https://user-images.githubusercontent.com/88894525/192122126-f4c85b63-92be-4059-8658-cf6a19a21e23.png)

2022-09-24 23:40 UTC, Alfredbis29 commented on styles.css
> +.button {
- [ ] The section has the margins (top, bottom, left, right) defined in the design , kindly use them as mentioned on figma design 😉

2022-09-26 10:11 UTC, topeogunleye requested changes
Hi @Mutai-Gilbert, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
- [ ] I kindly suggest that you change this `h3` to a `p` tag for semantics because this is a paragraph and not a header.

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
- [ ] I kindly suggest that you change this `h3` to a `p` tag for semantics because this is a paragraph and not a header.

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
- [ ] I kindly suggest that you change this `h3` to a `p` tag for semantics because this is a paragraph and not a header.

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
- [ ] I kindly suggest that you change this `h3` to a `p` tag for semantics because this is a paragraph and not a header.

2022-09-26 10:11 UTC, topeogunleye commented on styles.css
> +.on {
- [ ] I kindly suggest that you add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2` and on hover has the `background: #6070FF`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        <h1>About Myself</h1>
- [ ] There should be only one `h1` in an HTML file because of semantics and it helps search engines and web crawlers easily understand the main subject of your page. I kindly suggest that you make only your main title of "I'm Gilbert, Glad to See You!" an `h1` and kindly make use of headers from `h2` down to `h6` for any other headers in your HTML file.

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +      <div>
- [ ] I kindly suggest that you also use a `ul` as a general container for your `languages-ul` and ``frameworks` and also create and `li` tag container for your `languages-ul`, `Frameworks`. I'm suggested you need a 2 level nested ul and li

2022-09-26 10:11 UTC, topeogunleye commented on styles.css
> +.resume {
- [ ] I kindly suggest that you add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +    <div class="card">
I kindly suggest that you follow the Figma design template by ensuring this section has the margins (top, bottom, left, right) defined in the design and also has the font and colours (background and font) defined for the template. 

- [ ] Please ensure that your CANOPY project text has the same font size, weight and color as the project design.
- [ ] Please ensure that your BACK END DEV and 2015 text have a small circle by their left and use the same font weight and color as the Figma design
- [ ] Please ensure that your list of skills have the same text color, border radius and background color as the Figma design.
- [ ] Please add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:
![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

| Your Design | Figma Design |
| ------------- | ------------- |
| <img width="293" alt="image" src="https://user-images.githubusercontent.com/52934128/192246607-3353fdeb-3075-488d-8a5f-443b42d8aa6d.png">  | <img width="281" alt="image" src="https://user-images.githubusercontent.com/52934128/192246756-bc4927e7-4372-4a70-829e-b0d069c767b0.png">|

2022-09-26 10:11 UTC, topeogunleye commented on index.html
> +        Hello, I'm Gilbert Mutai a software developer! I can help you build a product , feature or website.Look through some of my work
- [ ] I kindly suggest that you ensure your about section has more spacing as seen in the Figma Design.
- [ ] I kindly suggest that you reduce the spacing between lets connect, icons and button.
- [ ] I kindly suggest that you make sure the text in your button is centered as seen in the Figma Design

| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="293" alt="image" src="https://user-images.githubusercontent.com/52934128/192250029-f368c81b-1514-43be-a5ee-e42b9d8c69b5.png">  | <img width="288" alt="image" src="https://user-images.githubusercontent.com/52934128/192249387-a98e5b28-4b5c-4c19-810a-f7f2ac791b86.png"> |

2022-09-27 19:10 UTC, Abenezer-Tilahun commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
Fixed.

2022-09-27 19:10 UTC, Abenezer-Tilahun commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
Fixed.

2022-09-27 19:11 UTC, Abenezer-Tilahun commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
Fixed.

2022-09-27 19:11 UTC, Abenezer-Tilahun commented on index.html
> +        <h3> A daily selection of privately personalized reads; no accounts or sign-ups required.</h3>
Fixed.

2022-09-27 19:12 UTC, Abenezer-Tilahun commented on styles.css
> +.on {
Done.

2022-09-27 19:13 UTC, Abenezer-Tilahun commented on index.html
> +        <h1>About Myself</h1>
Fixed.

2022-09-27 19:14 UTC, Abenezer-Tilahun commented on index.html
> +      <div>
Fixed.

2022-09-27 19:14 UTC, Abenezer-Tilahun commented on styles.css
> +.resume {
Done

2022-09-27 19:21 UTC, Abenezer-Tilahun commented on index.html
> +    <div class="card">
Fixed.

2022-09-27 19:21 UTC, Abenezer-Tilahun commented on index.html
> +        Hello, I'm Gilbert Mutai a software developer! I can help you build a product , feature or website.Look through some of my work
Fixed.

2022-09-27 19:22 UTC, Abenezer-Tilahun approved these changes
Hi @Mutai-Gilbert     , 

Your project is complete .  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional  README
✔️ Good Commit Messages


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 04:39 UTC, merged